import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import {
  AiOutlineGithub,
  AiFillInstagram,
  AiFillGoogleCircle,
} from "react-icons/ai";
import { BsFacebook, BsGithub } from "react-icons/bs";
import manwork from "../images/manWork.json";
import Lottie from "react-lottie";
import Typed from "react-typed";
import Work from "../components/Work";

const Home: NextPage = () => {
  const defaultOptions = {
    loop: true,
    autoplay: true,
    animationData: manwork,
    rendererSettings: {
      preserveAspectRatio: "xMidYMid slice",
    },
  };
  return (
    <div
      className={`pt-[6rem] xl:px-56 lg:px-56 md:px-56 sm:px-56 p-3 min-h-[120vh] transition duration-700 ease-in-out dark:bg-bgDark bg-yellowLight`}
    >
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <div className="flex w-full lg:flex-row md:flex-row xl:flex-row sm:flex-row flex-col-reverse  items-center justify-between gap-3">
        <div className=" xl:w-[60%] lg:w-[60%] sm:w-[60%] md:w-[60%] w-full  ">
          {/* bg-yellowCard dark:bg-blackLight */}
          <p className="text-[1.3rem] dark:text-slate-300 ">
            Hello, I&lsquo;m
            {/* Hello,Im */}
            <span className="font-bold pl-1 dark:text-white">
              Muhammad Bayou Satrio
            </span>
          </p>
          {/* <strong className="m-0 bg-yellow-400 px-1"> */}
          <Typed
            strings={["Front-end  Developer"]}
            typeSpeed={70}
            className="dark:text-white"
          />
          <div className="flex py-3 ">
            <div className="gap-3  flex justify-center items-center h-[70px]">
              <a
                href="https://github.com/bayustrio"
                target="_blank"
                className="cursor-pointer text-[1.4rem] bg-[#333333] p-2 rounded-full text-white"
              >
                <BsGithub className="" />
              </a>
              <a
                href="https://www.facebook.com/bayu.satrio.718689"
                target="_blank"
                className="cursor-pointer bg-[#4267B2] text-[1.4rem] p-2 rounded-full text-white"
              >
                <BsFacebook />
              </a>
              <a
                target="_blank"
                href="mailto:bayustrio7@gmail.com?subject=SendMail&body=Hello Muhammad Satrio"
                className="cursor-pointer bg-[#EA4234] text-white text-[1.4rem] p-2 rounded-full"
              >
                <AiFillGoogleCircle />
              </a>
              <a
                className="cursor-pointer bg-[#E4405F] text-[1.4rem] text-white p-2 rounded-full "
                target="_blank"
                href="https://www.instagram.com/bayuu.satrio/"
              >
                <AiFillInstagram height={15} />
              </a>
            </div>
          </div>
        </div>

        <div className="mx-auto  w-[200px] h-[200px] xl:w-[350px] xl:h-[350px] lg:w-[350px] lg:h-[350px] md:w-[300px] sm:w-[300px] sm:h-[300px] md:h-[300px] object-cover">
          <Lottie options={defaultOptions} />
        </div>
      </div>

      <div>
        <Work />
      </div>

      <footer className="p-6 text-center">
        <p className="text-slate-500 text-[0.9rem]">
          © 2022 Muhammad Bayou Satrio. All Rights Reserved.
        </p>
      </footer>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
};

export default Home;
