import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import manwork from "../images/manWork.json";
import Lottie from "react-lottie";
import Typed from "react-typed";

const Home: NextPage = () => {
  const defaultOptions = {
    loop: true,
    autoplay: true,
    animationData: manwork,
    rendererSettings: {
      preserveAspectRatio: "xMidYMid slice",
    },
  };
  return (
    <div
      className={`pt-[6rem] px-32 min-h-screen transition duration-700 ease-in-out dark:bg-bgDark bg-yellowLight`}
    >
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <div className="mx-auto w-[310px] h-[310px] xl:w-[400px] xl:h-[400px] lg:w-[400px] lg:h-[400px] md:w-[400px] sm:w-[400px] sm:h-[400px] md:h-[400px] object-cover">
        <Lottie options={defaultOptions} />
      </div>
      <div></div>
      <div className="bg-yellowCard dark:bg-blackLight w-full h-12 flex gap-2">
        <Typed
          strings={["Hello, I'm Front-end Developer based in Indonesia!"]}
          typeSpeed={40}
        />
      </div>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
};

export default Home;
